name: Test

on: [push, pull_request]

jobs:
  flake:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip and flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint the package
        run: |
          make flake
  test_one:
    needs: flake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Test the package
        run: |
          poetry install
          poetry run make test_all
  test:
    needs: test_one
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, ubuntu-18.04, macos-latest, windows-latest ]
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Test the package
        run: |
          poetry install
          poetry run make test_all
  test_success:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - run: echo Success!
