name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set up pip and poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Test the package
        - run: pipenv run make test_all
